### ISSUE TITLE
Chrome support?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CesarCapillas/alfresco-share-online-edition-addon#1]
```
In my company people mostly use chrome browser. Does the plugin support it?

```

Original issue reported on code.google.com by `skliarie@gmail.com` on 23 May 2013 at 4:47

**Comment by CesarCapillas** [comment]
As far I know, you need to register the url-scheme in Libreoffice application for Macosx (modifying the plist file and maybe declaring some listener in LO, for dealing with parameters). It is not straight-foward.
