### ISSUE TITLE
Use both versions

### ISSUE THREAD

**Issue by marciofoz** [CesarCapillas/alfresco-share-online-edition-addon#10]
Hi. 
It's possible to use the versions 0.2 and 0.3 at same time ? I have a lot of workstations with LO 4.X/Ubuntu 14.04 and now starting LO 5.X/Ubuntu 16.04.
Thank you.

**Comment by CesarCapillas** [comment]
Hi:

The protocol changes in Libreoffice 4.x client from dav:// to vnd.sun.star.webdav:// (in 5.x) so
the answer is not in principle, but with the new jar I think it is possible to work if ** no SSL activated ** in Alfresco. I tested this with LO 4.2.4.8 in Ubuntu 14.04, and LO 5.1.0.3 in Windows.

You can also to deploy the two jars at the same time, although you could modify a little bit the addon and create two different actions (:ugly:)

Regards.

--C.
