### ISSUE TITLE
How to build this module?

### ISSUE THREAD

**Issue by lmeunier** [CesarCapillas/alfresco-share-online-edition-addon#7]
Hi,

I would like to add the french translation. I"ve added the file `zk-online-edition_fr.properties`, but now I don't know how to build this module into a jar.
Any help is appreciated.

Thanks.
Laurent

**Comment by CesarCapillas** [comment]
Hi Laurent:

Thanks for your contribution.
You can pack it with jar command. Go into the directory that you unzipped or cloned via git:

$ cd alfresco-share-online-edition-addon
$ jar -cf alfresco-share-online-edition.jar * 

Place your properties file in alfresco/messages directory. I will upload a build.xml file, for packing it via ant.

Regards.

--C.

**Comment by lmeunier** [comment]
Hi,

Thank your for your quick answer.
I've just created a pull request to add the french translation.

Laurent
